### PR TITLE
Uplift plugin on items accidentally left in theme.

### LINKED ISSUE #129: Creating new comments when showing interface in tab not working CKAN 2.11.2
I have recently tried integrating this commenting extension into my CKAN instance and noticed a strange behaviour I have been unable to figure out. When I set the commenting interface to be shown inside a tab, new comments are not registered upon submit. It only shows comments that were already in the system. I can only create new comments when the interface is set to be on the same screen as the additional information table. I'm currently using CKAN 2.11.2 version.

### PR DESCRIPTION
**Pull request by duttonw**
Fixes #129

* Pull in jquery logic from theme
* Pull in updated comments list template which includes recaptcha
* Pull in css to show/hide comments correctly.
* Allow css/js overrides via templates

### CODE REVIEW

File: bin/local-serve.sh [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+}
+
+# Process Docker Compose configuration. This is used to avoid multiple
+# docker-compose.yml files.
+# Remove lines containing '###'.
+sed -i -e "/###/d" docker-compose.yml
+# Uncomment lines containing '##'.
+sed -i -e "s/##//" docker-compose.yml
+
+export CKAN_VERSION="2.11"
```
Comment (ThrawnCA) [inline bin/local-serve.sh:20]: Why hard-code this?

File: bin/local-update.sh [hunk 2]
```diff
@@ -0,0 +1,28 @@
+#!/usr/bin/env bash
+
+export CKAN_VERSION="2.11"
```
Comment (ThrawnCA) [inline bin/local-update.sh:3]: Why hard-code this?

File: ckanext/ytp/comments/helpers.py [hunk 3]
```diff
@@ -152,3 +159,28 @@ def get_comment_count_for_dataset(dataset_name, content_type='dataset'):
...
     comments_count = get_comment_count_for_dataset(dataset_name, content_type)
     return render_snippet('snippets/count_badge.html', {'count': comments_count})
+
+
+def is_reporting_enabled():
+    return _is_action_configured('report_list')
+
+
+def unreplied_comments_x_days(thread_url):
+    """A helper function for Data.Qld Engagement Reporting
```
Comment (ThrawnCA) [inline ckanext/ytp/comments/helpers.py:169]: This plugin shouldn't mention data.qld

File: ckanext/ytp/comments/plugin.py [hunk 4]
```diff
@@ -54,7 +54,10 @@ def get_helpers(self):
             'user_can_manage_comments': helpers.user_can_manage_comments,
             'get_org_id': helpers.get_org_id,
             'user_comment_follow_mute_status': notification_helpers.get_user_comment_follow_mute_status,
-            'ytp_comments_show_comments_tab_page': helpers.show_comments_tab_page
+            'ytp_comments_show_comments_tab_page': helpers.show_comments_tab_page,
+            'comment_notification_recipients_enabled':
```
Comment (ThrawnCA) [inline ckanext/ytp/comments/plugin.py:58]: This would double up with ckanext-data-qld until the latter is updated, will that cause problems?

**Review by ThrawnCA — CHANGES_REQUESTED** [review]

File: bin/local-serve.sh (hunk 1 above)
Comment (duttonw) [reply bin/local-serve.sh:20]: this is for my local testing, its not used in cicd and i did not have ahoy/amzee installed

File: ckanext/ytp/comments/plugin.py (hunk 4 above)
Comment (duttonw) [reply ckanext/ytp/comments/plugin.py:58]: we would need to do a 'lock-step' deployment with ytp and the theme to remove/add together. (or alt change its names)

File: bin/local-update.sh (hunk 2 above)
Comment (duttonw) [reply bin/local-update.sh:3]: this is for my local testing, its not used in cicd and i did not have ahoy/amzee installed

File: ckanext/ytp/comments/plugin.py (hunk 4 above)
Comment (ThrawnCA) [reply ckanext/ytp/comments/plugin.py:58]: I suggest using a slightly different name here than we used in ckanext-data-qld so they don't clash. Lock-step deployments are not ideal.

File: bin/local-update.sh (hunk 2 above)
Comment (ThrawnCA) [reply bin/local-update.sh:3]: It still could allow passing the version in, if `CKAN_VERSION` is already defined.

Comment (duttonw) [reply bin/local-update.sh:3]: ah, yep, it should be set if missing. I hard coded it.

File: docker-compose.yml [hunk 5]
```diff
@@ -34,13 +35,16 @@ services:
...
       - "5000"
+      # 0.0.0.0:5000:5000 # To access directly outside of amazeeio haproxy wiring
     image: *project
     <<: *default-volumes
     environment:
       <<: *default-environment
       AMAZEEIO_HTTP_PORT: 5000
       LAGOON_LOCALDEV_URL: "http://${PROJECT}.docker.amazee.io"
       AMAZEEIO_URL: "${PROJECT}.docker.amazee.io"
+    #command: # Used to start container but not serve so you can reboot without issues
```
Comment (duttonw) [inline docker-compose.yml:46]: @ThrawnCA , how could we make this be uncommented for 'local' run where we wish to be able to 'copy' in new code without doing a 'full' build again.

Comment (ThrawnCA) [reply docker-compose.yml:46]: I've never succeeded in doing that before, so I'm not sure, sorry, but if you do figure it out then I'll be quite interested.

File: ckanext/ytp/comments/plugin.py (hunk 4 above)
Comment (duttonw) [reply ckanext/ytp/comments/plugin.py]: done, add ytp_comments to the new helpers.

File: docker-compose.yml (hunk 5 above)
Comment (duttonw) [reply docker-compose.yml:46]: would have to be another sed pattern like #%# that is used for alt pattern.

**Review by ThrawnCA — APPROVED** [review]
